config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items
  get '/styles', to: 'items#styles', :as => 'styles_item_get'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :sub_categories
    has_many :items
    validates :name, presence: true
    validates :name, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  belongs_to :sub_category
  belongs_to :category
  validates :user, :sub_category, :category, :color, :photo, presence: true
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  has_many :items
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def index
        @items = Item.all.where(user_id: current_user).order('category_id','sub_category_id')
    end

    def new
        @user = current_user
        @item = Item.new
    end

    def create
        @user = current_user
        @item = Item.new(item_params)
        @item.user = @user
        if @item.save
            @item.save!
            redirect_to root_path
          else
            render "new"
          end
    end

    def edit
        @item = Item.find(params[:id])
    end

    def update
        @item = Item.find(params[:id])
        @item.update(item_params)
        redirect_to root_path
    end

    def destroy
        @item = Item.find(params[:id])
        @item.destroy
        redirect_to root_path
    end

    def styles
      @items = Item.all.where(user_id: current_user)
      @tops = @items.joins(:category).where(category: { name: "Tops" })
      @bottoms = @items.joins(:category).where(category: { name: "Bottoms" })
      @shoes = @items.joins(:category).where(category: { name: "Shoes" })
    end

    def all_tops
      @items = Item.all.where(user_id: current_user)
      @items.joins(:category).where(category: { name: "Tops" })
    end

    def all_shirts
      @items = Item.all.where(user_id: current_user)
      @items.joins(:sub_category).where(sub_category: { name: "Shirts" })
    end
    
    private

    def item_params
      params.require(:item).permit(:category_id, :sub_category_id, :color, :fabric, :favorite, :photo)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.html.erb
<div class="container">
  <div class="container pt-3 pb-3 d-flex justify-content-end">
    <%= link_to :back do %>
      <%= image_tag "cross-svgrepo-com.svg", style: 'height:20px;width:auto;' %>
    <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <img src="<%= cl_image_path @item.photo.key %>" width="100%" max-height="250px">
  </div>


  <div class="mt-5 mb-5">
    <%= simple_form_for (@item) do |f| %>
    <%= f.association :category,
            as: :radio_buttons,
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'} %>
      <%= f.association :sub_category %>
      <%= f.input :color, collection: ["Black", "White", "Bown", "Light grey", "Dark grey", "Beige", "Camel", "Brown", "Pink", "Navy", "Burgundy", "Forest green", "Red", "Orange", "Light blue", "Purple", "Green", "Yellow"] %>
      <%= f.input :fabric, collection: ["Cotton", "Leather", "Mixed fabric", "Jersey", "Linen", "Wool", "Merino Wool", "Polyester", "Satin", "Lycra", "Silk", "Suede", "Tweed", "Twill", "Velvet", "Cashmeer"] %>
      <%= f.input :favorite, input_html: { class: "toggle" } %>
      <%= f.input :photo, as: :file %>
      <input class="mt-5 btn btn-primary btn-lg btn-block" type="submit" name="commit" value="Save changes" data-disable-with="Update Item">
    <% end %> 
    <%= link_to item_path(@item), method: :delete, data: { confirm: "Are you sure?" } do %>
      <button type="button" class=" mt-5 btn btn-outline-dark btn-lg btn-block">Delete</button>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="container mt-5 mb-5">
    <div class="row">
        <% @items.each do |item| %>
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6 col-6">
                <div class="mb-4 d-flex justify-content-center" style="height:200px;">
                    <%= link_to edit_item_path(item) do %>
                        <img src="<%= cl_image_path item.photo.key %>" width="100%" height="100%">
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>
<div class="pt-3 pb-3" style="display:flex; justify-content:space-around; border-top:1px solid black; background-color:white;">
<%= link_to(root_path, class: "d-flex justify-content-center align-items-center flex-column") do %>
    <%= image_tag "closet-svgrepo-com.svg", style: 'height:40px;width:auto;' %>
    Closet
<% end %>
<%= link_to(new_item_path, class: "d-flex justify-content-center align-items-center flex-column") do %>
    <%= image_tag "plus-svgrepo-com.svg", style: 'height:40px;width:auto;' %>
    Add an item
<% end %>
<%= link_to(styles_item_get_path, class: "d-flex justify-content-center align-items-center flex-column") do %>
    <%= image_tag "clothes-rack-01-svgrepo-com.svg", style: 'height:40px;width:auto;' %>
    Change
<% end %>
</div>

app/views/items/new.html.erb
<div class="container" >
  <div class="container pt-3 pb-3 d-flex justify-content-end">
    <%= link_to :back do %>
      <%= image_tag "cross-svgrepo-com.svg", style: 'height:20px;width:auto;' %>
    <% end %>
  </div>

  <div class="mt-5 mb-5">
    <%= simple_form_for (@item) do |f| %>
      <%= f.association :category,
              as: :radio_buttons,
              collection_wrapper_tag: 'div',
              collection_wrapper_class: 'category-wrapper',
              item_wrapper_class: 'category-item',
              input_html: {class: 'category-selector'} %>
      <%= f.association :sub_category %>
      <%= f.input :color, collection: ["Black", "White", "Bown", "Light grey", "Dark grey", "Beige", "Camel", "Brown", "Pink", "Navy", "Burgundy", "Forest green", "Red", "Orange", "Light blue", "Purple", "Green", "Yellow"] %>
      <%= f.input :fabric, collection: ["Cotton", "Leather", "Mixed fabric", "Jersey", "Linen", "Wool", "Merino Wool", "Polyester", "Satin", "Lycra", "Silk", "Suede", "Tweed", "Twill", "Velvet", "Cashmeer"] %>
      <%= f.input :favorite, input_html: { class: "toggle" } %>
      <%= f.input :photo, as: :file %>
      <input class="mt-5 btn btn-primary btn-lg btn-block" type="submit" name="commit" value="Add to my closet" data-disable-with="Create Item">
    <% end %>
  </div>
</div>

app/views/items/styles.html.erb
  <div class="mb-5" style="height: 80vh; overflow:hidden; background-color:; display:flex; justify-content:space-evenly; flex-direction:column; margin-top:8px">
      <div id="carouselExampleControls1" class="carousel slide" data-ride="carousel" data-interval="false" style="width:100%; height:30vh">
        <div class="carousel-inner" style="height:100%;" >
          <% @tops.each_with_index do |item, index| %>
            <% if index == 0 %>
              <div class="carousel-item active" style="width:100%; height:100%; background-position: center; background-size:contain; background-repeat:no-repeat; background-image: url('<%= cl_image_path item.photo.key %>')">
              </div>
            <% else %>
              <div class="carousel-item" style="width:100%; height:100%; background-position: center; background-size:contain; background-repeat:no-repeat; background-image: url('<%= cl_image_path item.photo.key %>')">
              </div>
            <% end %>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls1" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls1" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <div id="carouselExampleControls2" class="carousel slide" data-ride="carousel" data-interval="false" style="width:100%; height:35vh">
        <div class="carousel-inner" style="height:100%;">
          <% @bottoms.each_with_index do |item, index| %>
            <% if index == 0 %>
              <div class="carousel-item active" style="width:100%; height:100%; background-position: center; background-size:contain; background-repeat:no-repeat; background-image: url('<%= cl_image_path item.photo.key %>')">

              </div>
            <% else %>
              <div class="carousel-item" style="width:100%; height:100%; background-position: center; background-size:contain; background-repeat:no-repeat; background-image: url('<%= cl_image_path item.photo.key %>')">
              </div>
            <% end %>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls2" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls2" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <div id="carouselExampleControls3" class="carousel slide" data-ride="carousel" data-interval="false" style="width:100%; height:15vh">
        <div class="carousel-inner" style="height:100%;">
          <% @shoes.each_with_index do |item, index| %>
            <% if index == 0 %>
              <div class="carousel-item active" style="width:100%; height:100%; background-position:center; background-size:contain; background-repeat: no-repeat; background-image: url('<%= cl_image_path item.photo.key %>')">
              </div>
            <% else %>
              <div class="carousel-item" style="width:100%; height:100%; background-position:center; background-size:contain; background-repeat: no-repeat; background-image: url('<%= cl_image_path item.photo.key %>')">
              </div>
            <% end %>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls3" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls3" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

  </div>
  <div class="pt-3 pb-3" style="display:flex; justify-content: space-around; border-top: 1px solid black; background-color:white;">
    <%= link_to(root_path, class: "d-flex justify-content-center align-items-center flex-column") do %>
      <%= image_tag "closet-svgrepo-com.svg", style: 'height:40px;width:auto;' %>
      Closet
    <% end %>
    <%= link_to(new_item_path, class: "d-flex justify-content-center align-items-center flex-column") do %>
      <%= image_tag "plus-svgrepo-com.svg", style: 'height:40px;width:auto;' %>
      Add an item
    <% end %>
    <%= link_to(styles_item_get_path, class: "d-flex justify-content-center align-items-center flex-column") do %>
      <%= image_tag "clothes-rack-01-svgrepo-com.svg", style: 'height:40px;width:auto;' %>
      Change
    <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minimylist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-5 mb-5">
    <h1>My closet</h1>
    <%= Item.count %> items
    <div class="container mt-5 mb-5 d-flex justify-content-center align-items-center flex-wrap">
        <% Item.all.each do |item| %>
            <%= link_to edit_item_path(item) do %>
                <div class="mb-4" style= "width:24%; min-height:250px; background-position: center; background-size: contain; background-repeat: no-repeat; background-image: url('<%= cl_image_path item.photo.key %>')"></div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "hanger-svgrepo-com.svg" %>
  <% end %>

  <%= link_to root_path, class: "navbar-brand" do %>
    <p style="font-family:'Pacifico'; font-size: 24px; margin:0px;">Minimylist</p>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar-svgrepo-com.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>